# Generated by Django 4.1.5 on 2023-03-03 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_foodeiblog_content', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='article_permission',
            field=models.BooleanField(default=False, verbose_name='Разрешение на показ'),
        ),
        migrations.AddField(
            model_name='article',
            name='ingredients',
            field=models.TextField(default='Null', verbose_name='Ингредиенты'),
        ),
        migrations.AlterField(
            model_name='article',
            name='text',
            field=models.TextField(verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='article',
            name='title',
            field=models.CharField(max_length=256, verbose_name='Название рецепта'),
        ),
    ]
