# Generated by Django 4.1.5 on 2023-03-03 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_foodeiblog_content', '0002_article_article_permission_article_ingredients_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='ingredients',
            field=models.TextField(default='Ингредиенты:', verbose_name='Ингредиенты'),
        ),
    ]
